// Generated by gencpp from file rosserial_arduino/motorResponse.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_MOTORRESPONSE_H
#define ROSSERIAL_ARDUINO_MESSAGE_MOTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_arduino
{
template <class ContainerAllocator>
struct motorResponse_
{
  typedef motorResponse_<ContainerAllocator> Type;

  motorResponse_()
    : done()  {
    }
  motorResponse_(const ContainerAllocator& _alloc)
    : done(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::rosserial_arduino::motorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_arduino::motorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motorResponse_

typedef ::rosserial_arduino::motorResponse_<std::allocator<void> > motorResponse;

typedef boost::shared_ptr< ::rosserial_arduino::motorResponse > motorResponsePtr;
typedef boost::shared_ptr< ::rosserial_arduino::motorResponse const> motorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_arduino::motorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_arduino::motorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_arduino': ['/home/lab/Documents/Data_reforement_code/my/src/rosserial/rosserial_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::motorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::motorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::motorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6f8833c91017f802acaa131839007d";
  }

  static const char* value(const ::rosserial_arduino::motorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6f8833c91017f8ULL;
  static const uint64_t static_value2 = 0x02acaa131839007dULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_arduino/motorResponse";
  }

  static const char* value(const ::rosserial_arduino::motorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string done\n\
\n\
";
  }

  static const char* value(const ::rosserial_arduino::motorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_arduino::motorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_arduino::motorResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_MOTORRESPONSE_H
