// Generated by gencpp from file rosserial_arduino/motorRequest.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_MOTORREQUEST_H
#define ROSSERIAL_ARDUINO_MESSAGE_MOTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_arduino
{
template <class ContainerAllocator>
struct motorRequest_
{
  typedef motorRequest_<ContainerAllocator> Type;

  motorRequest_()
    : Move()  {
    }
  motorRequest_(const ContainerAllocator& _alloc)
    : Move(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Move_type;
  _Move_type Move;





  typedef boost::shared_ptr< ::rosserial_arduino::motorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_arduino::motorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motorRequest_

typedef ::rosserial_arduino::motorRequest_<std::allocator<void> > motorRequest;

typedef boost::shared_ptr< ::rosserial_arduino::motorRequest > motorRequestPtr;
typedef boost::shared_ptr< ::rosserial_arduino::motorRequest const> motorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_arduino::motorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_arduino::motorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_arduino': ['/home/lab/Documents/Data_reforement_code/my/src/rosserial/rosserial_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::motorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::motorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::motorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fba89113294e9937d5a469e528e7df7";
  }

  static const char* value(const ::rosserial_arduino::motorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fba89113294e993ULL;
  static const uint64_t static_value2 = 0x7d5a469e528e7df7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_arduino/motorRequest";
  }

  static const char* value(const ::rosserial_arduino::motorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Move\n\
";
  }

  static const char* value(const ::rosserial_arduino::motorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_arduino::motorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_arduino::motorRequest_<ContainerAllocator>& v)
  {
    s << indent << "Move: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_MOTORREQUEST_H
