// Generated by gencpp from file rosserial_arduino/motor.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_MOTOR_H
#define ROSSERIAL_ARDUINO_MESSAGE_MOTOR_H

#include <ros/service_traits.h>


#include <rosserial_arduino/motorRequest.h>
#include <rosserial_arduino/motorResponse.h>


namespace rosserial_arduino
{

struct motor
{

typedef motorRequest Request;
typedef motorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor
} // namespace rosserial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_arduino::motor > {
  static const char* value()
  {
    return "58ba11ff6615accf86f4ea6f489aba40";
  }

  static const char* value(const ::rosserial_arduino::motor&) { return value(); }
};

template<>
struct DataType< ::rosserial_arduino::motor > {
  static const char* value()
  {
    return "rosserial_arduino/motor";
  }

  static const char* value(const ::rosserial_arduino::motor&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_arduino::motorRequest> should match 
// service_traits::MD5Sum< ::rosserial_arduino::motor > 
template<>
struct MD5Sum< ::rosserial_arduino::motorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::motor >::value();
  }
  static const char* value(const ::rosserial_arduino::motorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::motorRequest> should match 
// service_traits::DataType< ::rosserial_arduino::motor > 
template<>
struct DataType< ::rosserial_arduino::motorRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::motor >::value();
  }
  static const char* value(const ::rosserial_arduino::motorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_arduino::motorResponse> should match 
// service_traits::MD5Sum< ::rosserial_arduino::motor > 
template<>
struct MD5Sum< ::rosserial_arduino::motorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::motor >::value();
  }
  static const char* value(const ::rosserial_arduino::motorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::motorResponse> should match 
// service_traits::DataType< ::rosserial_arduino::motor > 
template<>
struct DataType< ::rosserial_arduino::motorResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::motor >::value();
  }
  static const char* value(const ::rosserial_arduino::motorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_MOTOR_H
