// Generated by gencpp from file my_controll/commandResponse.msg
// DO NOT EDIT!


#ifndef MY_CONTROLL_MESSAGE_COMMANDRESPONSE_H
#define MY_CONTROLL_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_controll
{
template <class ContainerAllocator>
struct commandResponse_
{
  typedef commandResponse_<ContainerAllocator> Type;

  commandResponse_()
    : done(0)  {
    }
  commandResponse_(const ContainerAllocator& _alloc)
    : done(0)  {
  (void)_alloc;
    }



   typedef int64_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::my_controll::commandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_controll::commandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct commandResponse_

typedef ::my_controll::commandResponse_<std::allocator<void> > commandResponse;

typedef boost::shared_ptr< ::my_controll::commandResponse > commandResponsePtr;
typedef boost::shared_ptr< ::my_controll::commandResponse const> commandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_controll::commandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_controll::commandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_controll

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_controll::commandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_controll::commandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_controll::commandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_controll::commandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controll::commandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controll::commandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_controll::commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "451104427704de2eb28d1a5e0b6e1832";
  }

  static const char* value(const ::my_controll::commandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x451104427704de2eULL;
  static const uint64_t static_value2 = 0xb28d1a5e0b6e1832ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_controll::commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_controll/commandResponse";
  }

  static const char* value(const ::my_controll::commandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_controll::commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 done\n\
\n\
";
  }

  static const char* value(const ::my_controll::commandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_controll::commandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct commandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_controll::commandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_controll::commandResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<int64_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CONTROLL_MESSAGE_COMMANDRESPONSE_H
