// Generated by gencpp from file my_controll/command.msg
// DO NOT EDIT!


#ifndef MY_CONTROLL_MESSAGE_COMMAND_H
#define MY_CONTROLL_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <my_controll/commandRequest.h>
#include <my_controll/commandResponse.h>


namespace my_controll
{

struct command
{

typedef commandRequest Request;
typedef commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command
} // namespace my_controll


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_controll::command > {
  static const char* value()
  {
    return "4243c91da84ec104deba2b49ffd24ad2";
  }

  static const char* value(const ::my_controll::command&) { return value(); }
};

template<>
struct DataType< ::my_controll::command > {
  static const char* value()
  {
    return "my_controll/command";
  }

  static const char* value(const ::my_controll::command&) { return value(); }
};


// service_traits::MD5Sum< ::my_controll::commandRequest> should match 
// service_traits::MD5Sum< ::my_controll::command > 
template<>
struct MD5Sum< ::my_controll::commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_controll::command >::value();
  }
  static const char* value(const ::my_controll::commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_controll::commandRequest> should match 
// service_traits::DataType< ::my_controll::command > 
template<>
struct DataType< ::my_controll::commandRequest>
{
  static const char* value()
  {
    return DataType< ::my_controll::command >::value();
  }
  static const char* value(const ::my_controll::commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_controll::commandResponse> should match 
// service_traits::MD5Sum< ::my_controll::command > 
template<>
struct MD5Sum< ::my_controll::commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_controll::command >::value();
  }
  static const char* value(const ::my_controll::commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_controll::commandResponse> should match 
// service_traits::DataType< ::my_controll::command > 
template<>
struct DataType< ::my_controll::commandResponse>
{
  static const char* value()
  {
    return DataType< ::my_controll::command >::value();
  }
  static const char* value(const ::my_controll::commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_CONTROLL_MESSAGE_COMMAND_H
