// Generated by gencpp from file my_controll/commandRequest.msg
// DO NOT EDIT!


#ifndef MY_CONTROLL_MESSAGE_COMMANDREQUEST_H
#define MY_CONTROLL_MESSAGE_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_controll
{
template <class ContainerAllocator>
struct commandRequest_
{
  typedef commandRequest_<ContainerAllocator> Type;

  commandRequest_()
    : command()
    , name()
    , channel(0)  {
    }
  commandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , name(_alloc)
    , channel(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int64_t _channel_type;
  _channel_type channel;





  typedef boost::shared_ptr< ::my_controll::commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_controll::commandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct commandRequest_

typedef ::my_controll::commandRequest_<std::allocator<void> > commandRequest;

typedef boost::shared_ptr< ::my_controll::commandRequest > commandRequestPtr;
typedef boost::shared_ptr< ::my_controll::commandRequest const> commandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_controll::commandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_controll::commandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_controll

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_controll::commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_controll::commandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_controll::commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_controll::commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controll::commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controll::commandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_controll::commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b5eb880e7fb135b176dcc12bd5ba1a";
  }

  static const char* value(const ::my_controll::commandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b5eb880e7fb135ULL;
  static const uint64_t static_value2 = 0xb176dcc12bd5ba1aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_controll::commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_controll/commandRequest";
  }

  static const char* value(const ::my_controll::commandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_controll::commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
string name\n\
int64 channel\n\
";
  }

  static const char* value(const ::my_controll::commandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_controll::commandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.name);
      stream.next(m.channel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct commandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_controll::commandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_controll::commandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "channel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.channel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CONTROLL_MESSAGE_COMMANDREQUEST_H
